name: Build
on:
  workflow_dispatch:
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          rm -rf package-lock.json
          npm install
      - name: Run application
        run: npm start&
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: http://localhost:3000/
